# Generated by Django 3.2.18 on 2023-02-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['name'], 'verbose_name': 'Имеющиеся книги', 'verbose_name_plural': 'Имеющиеся книги'},
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='messenger.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликованность'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='books',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='messenger.category'),
        ),
    ]
