# Generated by Django 3.2.18 on 2023-02-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['name'], 'verbose_name': 'Имеющиеся книги', 'verbose_name_plural': 'Имеющиеся книги'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликованность'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
