# Generated by Django 3.2.18 on 2023-02-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20230223_1200'),
        ('messenger', '0002_auto_20230223_1437'),
    ]

    operations = [
    ]
