# Generated by Django 3.2.18 on 2023-02-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20230226_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
