# Generated by Django 3.2.18 on 2023-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(default='не выбрано', help_text='Select a genre for this book', to='messenger.Genre', verbose_name='Жанр книги'),
        ),
    ]
